package com.trackr.app.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Material 3 "Cinematic Dark" tokens (exact values from the Stitch Tailwind config) ----
val StitchSurface = Color(0xFF111317)
val StitchSurfaceLowest = Color(0xFF0C0E12)
val StitchSurfaceLow = Color(0xFF1A1C20)
val StitchSurfaceContainer = Color(0xFF1E2024)
val StitchSurfaceHigh = Color(0xFF282A2E)
val StitchSurfaceHighest = Color(0xFF333539)
val StitchSurfaceBright = Color(0xFF37393E)
val StitchOnSurface = Color(0xFFE2E2E8)
val StitchOnSurfaceVariant = Color(0xFFC9C4D8)
val StitchOutline = Color(0xFF938EA1)
val StitchOutlineVariant = Color(0xFF484555)
val StitchPrimary = Color(0xFFCABEFF)
val StitchOnPrimary = Color(0xFF31009A)
val StitchPrimaryContainer = Color(0xFF947DFF)
val StitchOnPrimaryContainer = Color(0xFF2A0088)
val StitchInversePrimary = Color(0xFF603CE2)
val StitchSecondary = Color(0xFFFFB955)
val StitchOnSecondary = Color(0xFF452B00)
val StitchSecondaryContainer = Color(0xFFC48313)
val StitchOnSecondaryContainer = Color(0xFF3C2500)
val StitchTertiary = Color(0xFF7BD0FF)
val StitchOnTertiary = Color(0xFF00354A)
val StitchTertiaryContainer = Color(0xFF009BD1)
val StitchOnTertiaryContainer = Color(0xFF002D40)
val StitchError = Color(0xFFFFB4AB)
val StitchOnError = Color(0xFF690005)
val StitchErrorContainer = Color(0xFF93000A)
val StitchOnErrorContainer = Color(0xFFFFDAD6)

// ---- Brand / semantic colors (DESIGN.md prose) ----
val BrandViolet = Color(0xFF7C5CFF)
val RatingAmber = Color(0xFFFFB547)
val StatusWatching = Color(0xFF38BDF8)
val StatusCompleted = Color(0xFF22C55E)
val StatusPlan = Color(0xFFA855F7)
val StatusDropped = Color(0xFFEF4444)

// ---- Light palette (same hues, tuned for light surfaces) ----
val LightSurface = Color(0xFFFBF8FF)
val LightSurfaceLowest = Color(0xFFFFFFFF)
val LightSurfaceLow = Color(0xFFF5F2FB)
val LightSurfaceContainer = Color(0xFFEFEDF6)
val LightSurfaceHigh = Color(0xFFE9E7F0)
val LightSurfaceHighest = Color(0xFFE3E1EA)
val LightOnSurface = Color(0xFF1A1B21)
val LightOnSurfaceVariant = Color(0xFF47464F)
val LightOutline = Color(0xFF787680)
val LightOutlineVariant = Color(0xFFC9C5D0)
val LightPrimary = Color(0xFF603CE2)
val LightPrimaryContainer = Color(0xFFE6DEFF)
val LightOnPrimaryContainer = Color(0xFF1C0062)
val LightSecondary = Color(0xFF8A5100)
val LightTertiary = Color(0xFF006688)
